$LOAD_PATH.unshift File.join(File.dirname(__FILE__), 'lib')
require 'wraith'
require 'bundler/gem_tasks'



@config = ('config')

desc 'Execute wraith on two sites with a config you specify'
task :config, [:yaml] do |_t, custom|
  custom.with_defaults(:yaml => 'config')
  @config = "#{custom[:yaml]}"
  Rake::Task['default'].invoke
end

task :default => [:getallconfig, :history, :latest] do
  puts 'Done!'
end


desc 'Execute wraith on a single site, no image diffs, with a config you specify'
task :grabber, [:yaml] do |_t, custom|
  custom.with_defaults(:yaml => 'config')
  @config = "#{custom[:yaml]}"
  Rake::Task['grab'].invoke
end

